from os import environ
from dotenv import load_dotenv

load_dotenv()

HEIM_COIN_SECRET=environ.get('HEIM_COIN_SECRET')
HEIM_COIN_PRIVATE_KEY_PASS_PHRASE=environ.get('HEIM_COIN_PRIVATE_KEY_PASS_PHRASE')
FLASK_RUN_HOST=environ.get('FLASK_RUN_HOST')
FLASK_RUN_PORT=environ.get('FLASK_RUN_PORT')
HEIM_COIN_DB_NAME=environ.get('HEIM_COIN_DB_NAME')
HEIM_COIN_DB_USERNAME=environ.get('HEIM_COIN_DB_USERNAME')
HEIM_COIN_DB_PASSWORD=environ.get('HEIM_COIN_DB_PASSWORD')
HEIM_COIN_DB_HOST=environ.get('HEIM_COIN_DB_HOST')
HEIM_COIN_NET=environ.get('HEIM_COIN_NET')

FLASK_ENV=environ.get('FLASK_ENV')
FLASK_DEBUG=environ.get('FLASK_DEBUG')
FLASK_RELOAD=environ.get('FLASK_RELOAD')
FLASK_APP=environ.get('FLASK_APP')
